project:
  type: website
  output-dir: docs

website:
  title: "David Osborne"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual
