---
title: "Publications"
---

-   Osborne, D. A. (2013) *Fallow Deer in Iron Age and Roman Britain: a study of fallow deer antlers using stable isotopes*. Unpublished MSc dissertation, University of Nottingham. DOI: [10.5281/zenodo.812350](https://doi.org/10.5281/zenodo.812350)

-   Miller, H., Carden, R. F., Evans, J., Lamb, A., Madgwick, R., Osborne, D., Symmons, R. and Sykes, N. (2015) Dead or alive? Investigating long-distance transport of live fallow deer and their body parts in antiquity. *Environmental Archaeology* **21**(3), 246--259. DOI: [10.1179/1749631414Y.0000000043](https://doi.org/10.1179/1749631414Y.0000000043)

-   Osborne, D. (2017) Imports and isotopes: a modern baseline study for interpreting Iron Age and Roman trade in fallow deer antlers. *Papers from the Institute of Archaeology* **27**(1): Article 10, 1--15. DOI: [10.5334/pia-482](https://doi.org/10.5334/pia-482 "10.5334/pia-482")

-   Osborne, D. (2023) *When* did *the cows come home?* British Geological Survey blog. URL: [https://www.bgs.ac.uk/news/when-did-the-cows-come-home/](#0) (accessed 2023-02-23)

-   Osborne, D. (2023) When did the cows come home? Exploring Bronze Age animal husbandry with isotopes and X-rays. *PAST: The newsletter of the Prehistoric Society* **103**, 12--13**.** URL: [**https://www.prehistoricsociety.org/publications/past/103**](https://www.prehistoricsociety.org/publications/past/103){.uri} (accessed 2023-09-14)

-   Osborne, D. (2023) Book review: *Footmarks: a journey into our restless past* by Jim Leary. *Folk Life: Journal of Ethnological Studies* 61(2), 199-200. DOI: [10.1080/04308778.2023.2251254](https://doi.org/10.1080/04308778.2023.2251254)

-   Osborne, D. (submitted) 'The cow that lived': animal care and welfare in prehistoric Britain, in: Mannermaa, K., Armstrong Oma, K., Brusgaard, N. and Kirkinen, T. (eds.) *Archaeological Perspectives on Animal Welfare.* London:Bloomsbury.
